export const {
  PORT,
  MONGO_URI,
  CORS_ORIGIN,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  NODEMAILER_USER,
  NODEMAILER_PASS,
  REDIS_URL,
  REDIS_PASSWORD,
  REDIS_PORT,
  REDIS_EXPIRATION
} = process.env;
